"""This is a dictionary of sample paragraph texts that can be chosen by a user to display on the screen"""

text_dict = {
    "The Great Adventure": " As the sun rose over the rugged mountains, a group of adventurers set out on their journey. They had been planning this trip for months, and excitement coursed through their veins. The terrain was challenging, but the sights were breathtaking. They trekked through dense forests, crossed rushing rivers, and climbed steep cliffs. Along the way, they encountered all kinds of wildlife, from majestic eagles to curious squirrels. At night, they huddled around the campfire, sharing stories and roasting marshmallows. By the end of their adventure, they were exhausted but exhilarated, filled with a sense of accomplishment that would stay with them for years to come",
    "The Ultimate Recipe": " In a cozy kitchen, a chef was hard at work on his latest creation. He had spent years perfecting this recipe, and he was determined to make it the best it could be. He started by carefully selecting the freshest ingredients, chopping, mixing, and measuring with precision. The smells wafting from the oven were mouth-watering, and the taste was even better. With each bite, the flavors exploded in your mouth, a perfect blend of savory and sweet. When the chef finally presented his dish to his guests, they were blown away. They had never tasted anything like it before, and they all begged for the recipe.",
    "The Secret Garden": "Tucked away in a quiet corner of the city was a beautiful garden. It was a secret oasis, hidden from the hustle and bustle of everyday life. The garden was a riot of color, with blooming flowers, fluttering butterflies, and chirping birds. There were hidden nooks and crannies to explore, shady spots to relax in, and gurgling fountains to admire. As you walked through the garden, you could feel your worries melt away. It was a peaceful, calming space, where you could connect with nature and find your inner peace.",
    "Missing Diamond": "The diamond was gone, and nobody knew where it had gone. It had been locked in a secure safe, guarded around the clock by a team of experts. But when the safe was opened, the diamond was nowhere to be found. The room was in disarray, the lock on the safe had been tampered with, and there were no clues to be found. The police were called in, and they questioned everyone who had access to the room. But nobody had seen anything suspicious. It was a mystery that would baffle investigators for months, until a clever detective finally cracked the case.",
    " Race of a Lifetime": "The runners gathered at the starting line, nerves jangling with excitement. They had trained for months, pushing their bodies to the limit to prepare for this moment. The crowd roared as the starting gun sounded, and the runners took off like a shot. The course was challenging, with steep hills, tight turns, and unpredictable weather. But the runners were determined, gritting their teeth and pushing through the pain. As they neared the finish line, the tension was almost unbearable. In the end, there could only be one winner, but every runner who crossed that finish line was a hero in their own right.",
}
